language: cpp
install:
    - git submodule update --remote
    - wget https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz && tar xzf cmake-3.6.2-Linux-x86_64.tar.gz
script:
    - cmake-3.6.2-Linux-x86_64/bin/cmake -DBUILD_TESTS=ON && make
    - ./tests/sctests
