language: cpp
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost-dev
        - g++-6
install:
    - wget --no-check-certificate https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz
    - tar xzf cmake-3.6.2-Linux-x86_64.tar.gz
script:
    - cd tests
    - export CXX=g++-6
    - ../cmake-3.6.2-Linux-x86_64/bin/cmake . && make
    - ./sctests
